import {
  faBell,
  faBug,
  faCheck,
  faCloud,
  faCloudRain,
  faDroplet,
  faFileLines,
  faHospital,
  faLocationDot,
  faMapLocationDot,
  faPhone,
  faRoute,
  faSliders,
  faTemperatureThreeQuarters,
  faTriangleExclamation,
  faWind,
  faXmark,
  faCircleInfo,
} from "@fortawesome/free-solid-svg-icons";

export {
  faBell,
  faBug,
  faCheck,
  faCircleInfo,
  faCloud,
  faCloudRain,
  faDroplet,
  faFileLines,
  faHospital,
  faLocationDot,
  faMapLocationDot,
  faPhone,
  faRoute,
  faSliders,
  faTemperatureThreeQuarters,
  faTriangleExclamation,
  faWind,
  faXmark,
};
